// Code generated by runnerq-spec tools/gen from constants/constants.json. DO NOT EDIT.

// Package spec holds the constants every RunnerQ implementation shares
// (github.com/runnerq/runnerq-spec).
package spec

// Version is the runnerq-spec release these constants come from.
const Version = "0.7.0"

// SchemaAdvisoryLockKey is the Postgres advisory lock every implementation
// holds while it creates, migrates or checks the schema (0x52554E4E45525121,
// "RUNNERQ!").
const SchemaAdvisoryLockKey int64 = 5932734182207934753

// WorkChannelPrefix is the prefix of a queue's LISTEN/NOTIFY channel
// announcing committed runnable work. The queue name follows.
const WorkChannelPrefix = "rq_w_"

// ResultChannelPrefix is the prefix of a queue's LISTEN/NOTIFY channel
// announcing committed results; the payload is comma-joined activity IDs. The
// queue name follows.
const ResultChannelPrefix = "rq_r_"

// DefaultMaxRetryDelaySeconds is the cap on retry backoff when an activity
// sets none (max_retry_delay_seconds 0); vectors/retry_delay.json.
const DefaultMaxRetryDelaySeconds = 3600

// BusinessKeyPrefix is the prefix of an encoded application idempotency key
// (vectors/business_key.json).
const BusinessKeyPrefix = "rq:key:v2:"

// StepKeyPrefix is the prefix of the idempotency key derived for an activity
// spawned by a step (vectors/step_key.json). Not an application key.
const StepKeyPrefix = "rq:step:"

// SerializationJSON is the plain JSON serialization. An empty serialization
// means the same.
const SerializationJSON = "json-v1"

// SerializationSuperJSON is the TypeScript SDK's serialization: a SuperJSON
// {json, meta} envelope.
const SerializationSuperJSON = "superjson-v1"

// The kinds of storage error. The numbers are stored (runnerq_commands
// err_kind) and sent on the wire, so they never change.
const (
	StorageErrorKindUnavailable         = 0
	StorageErrorKindConflict            = 1
	StorageErrorKindNotFound            = 2
	StorageErrorKindInternal            = 3
	StorageErrorKindSerialization       = 4
	StorageErrorKindConfiguration       = 5
	StorageErrorKindTimeout             = 6
	StorageErrorKindDuplicateActivity   = 7
	StorageErrorKindIdempotencyConflict = 8
	StorageErrorKindClaimLost           = 9
	StorageErrorKindCheckpointConflict  = 10
	StorageErrorKindInvalidArgument     = 11
	StorageErrorKindUnsupported         = 12
)
